# Generated by Django 6.0.4 on 2026-05-04 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mesh_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('status', models.CharField(default='online', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('mesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.mesh')),
            ],
        ),
        migrations.CreateModel(
            name='SetupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mesh')),
            ],
        ),
    ]
